# Generated by Django 4.2.30 on 2026-09-16 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('storage_limit_bytes', models.BigIntegerField(default=524288000)),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('daily_conversion_limit', models.IntegerField(default=50)),
                ('monthly_conversion_limit', models.IntegerField(default=500)),
                ('daily_conversion_count', models.IntegerField(default=0)),
                ('monthly_conversion_count', models.IntegerField(default=0)),
                ('last_conversion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
