# Generated by Django 4.2.30 on 2026-09-13 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key for anonymous user job ownership.', max_length=40)),
                ('source_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image')], help_text='Format of the uploaded file.', max_length=20)),
                ('target_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image')], help_text='Desired output format.', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('original_filename', models.CharField(help_text='Original filename as provided by the user. Metadata only.', max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, help_text='Size of the uploaded file in bytes. Stored for auditing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the conversion engine began processing.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the conversion finished (succeeded or failed).', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Engine error details. Empty unless status is 'failed'.")),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous users. Set when the user is logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Job',
                'verbose_name_plural': 'Conversion Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'status'], name='conversions_session_93b347_idx'), models.Index(fields=['user', 'status'], name='conversions_user_id_4fde08_idx')],
            },
        ),
    ]
