# Generated by Django 4.2.30 on 2026-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='input_path',
            field=models.CharField(blank=True, help_text='Absolute path to the staged input file on disk. Internal use only — never exposed through the API.', max_length=1024),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='output_filename',
            field=models.CharField(blank=True, help_text='Safe output filename presented to the user for download.', max_length=255),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='output_path',
            field=models.CharField(blank=True, help_text='Absolute path to the generated output file on disk. Internal use only — never exposed through the API.', max_length=1024),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='output_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size of the generated output file in bytes.', null=True),
        ),
    ]
