# Generated by Django 4.2.30 on 2026-09-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0002_add_file_path_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Optional parameters for conversion engine (e.g. resize, quality).'),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='source_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image'), ('csv', 'CSV Document'), ('webp', 'WebP Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive')], help_text='Format of the uploaded file.', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='target_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image'), ('csv', 'CSV Document'), ('webp', 'WebP Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive')], help_text='Desired output format.', max_length=20),
        ),
    ]
