# Generated by Django 4.2.30 on 2026-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0003_conversionjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='source_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image'), ('csv', 'CSV Document'), ('webp', 'WebP Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive'), ('txt', 'Text File (TXT)'), ('html', 'HTML Document'), ('md', 'Markdown Document')], help_text='Format of the uploaded file.', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='target_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word (DOCX)'), ('xlsx', 'Excel (XLSX)'), ('pptx', 'PowerPoint (PPTX)'), ('jpg', 'JPG Image'), ('png', 'PNG Image'), ('csv', 'CSV Document'), ('webp', 'WebP Image'), ('bmp', 'BMP Image'), ('tiff', 'TIFF Image'), ('gif', 'GIF Image'), ('zip', 'ZIP Archive'), ('txt', 'Text File (TXT)'), ('html', 'HTML Document'), ('md', 'Markdown Document')], help_text='Desired output format.', max_length=20),
        ),
    ]
