# Generated by Django 4.2.30 on 2026-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0004_alter_conversionjob_source_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the job was cancelled.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', help_text='Associated Celery task UUID.', max_length=255),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='current_stage',
            field=models.CharField(blank=True, default='', help_text='Human readable stage identifier.', max_length=64),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='error_code',
            field=models.CharField(blank=True, default='', help_text='Machine-readable error code.', max_length=64),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the output file or job metadata expires.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='When the job reached FAILED status.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, help_text='Last active heartbeat timestamp from worker.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed retries.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='progress',
            field=models.IntegerField(default=0, help_text='Job progress percentage 0-100.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of retry attempts executed.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='stage_message',
            field=models.CharField(blank=True, default='', help_text='Detailed stage status message.', max_length=255),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='worker_name',
            field=models.CharField(blank=True, default='', help_text='Name of worker that processed the task.', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='queued', max_length=20),
        ),
    ]
