# Generated by Django 4.2.30 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0005_conversionjob_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancel_requested', 'Cancel Requested'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
