# Generated by Django 4.2.30 on 2026-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0006_alter_conversionjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='input_storage_key',
            field=models.CharField(blank=True, help_text='Object storage key for the staged input file.', max_length=1024),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='is_finalized',
            field=models.BooleanField(default=True, help_text='False for pending direct presigned upload sessions until finalization.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='output_storage_key',
            field=models.CharField(blank=True, help_text='Object storage key for the generated output file.', max_length=1024),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='storage_backend',
            field=models.CharField(default='local', help_text="Storage provider backend used ('local', 's3').", max_length=32),
        ),
    ]
