# Generated by Django 4.2.30 on 2026-09-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0007_conversionjob_input_storage_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversionjob',
            name='conversions_session_93b347_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversionjob',
            name='conversions_user_id_4fde08_idx',
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='cleanup_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of cleanup execution attempts.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='cleanup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When file cleanup execution completed.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='cleanup_error',
            field=models.TextField(blank=True, help_text='Diagnostic cleanup failure message if status is failed.'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='cleanup_started_at',
            field=models.DateTimeField(blank=True, help_text='When file cleanup execution started.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='cleanup_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_required', 'Not Required')], db_index=True, default='not_required', help_text='Status of file cleanup lifecycle.', max_length=20),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['user', 'created_at'], name='conversions_user_id_c60972_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['session_key', 'created_at'], name='conversions_session_9d6c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['user', 'status', 'created_at'], name='conversions_user_id_fab37d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['session_key', 'status', 'created_at'], name='conversions_session_752f57_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'expires_at'], name='conversions_status_af91d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['cleanup_status', 'expires_at'], name='conversions_cleanup_247ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'last_heartbeat'], name='conversions_status_977fa5_idx'),
        ),
    ]
