# Generated by Django 4.2.30 on 2026-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversions', '0008_remove_conversionjob_conversions_session_93b347_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='duration_ms',
            field=models.PositiveBigIntegerField(blank=True, help_text='Total execution duration in milliseconds.', null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='error_category',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Taxonomy category for error classification.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['status', 'created_at'], name='conversions_status_b1af7c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['error_category', 'created_at'], name='conversions_error_c_a9d79c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['started_at'], name='conversions_started_62715a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionjob',
            index=models.Index(fields=['completed_at'], name='conversions_complet_2aa14b_idx'),
        ),
    ]
