"""
Phase 2 tests — real PDF → DOCX conversion engine.

These tests use actual PDF fixtures generated by reportlab to exercise the
full conversion pipeline: upload → stage → engine → output → download.

No mocking of the conversion function itself.
The engine must produce a real, parseable DOCX file.
"""

import io
import os
import tempfile
import uuid
from pathlib import Path

import django
from django.test import TestCase, override_settings
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APIClient

from apps.conversions.engines.base import BaseConversionEngine, ConversionError
from apps.conversions.engines.pdf_to_docx import PdfToDocxEngine
from apps.conversions.engines.registry import EngineRegistry
from apps.conversions.engines.validators import validate_pdf_signature, validate_output_file
from apps.conversions.fixtures.generate_fixtures import (
    generate_simple_text_pdf,
    generate_multipage_pdf,
    generate_table_pdf,
    generate_image_pdf,
    REPORTLAB_AVAILABLE,
)
from apps.conversions.models import ConversionJob, JobStatus
from apps.conversions.services import ConversionService

# ── Temp dir used for all Phase 2 tests ───────────────────────────────────────
TEST_TEMP_DIR = tempfile.mkdtemp(prefix="velto_phase2_tests_")


def setUpModule():
    """Generate PDF fixtures once before any Phase 2 test runs."""
    if not REPORTLAB_AVAILABLE:
        import warnings
        warnings.warn("reportlab not installed — real-PDF tests will be skipped.")
        return
    from apps.conversions.fixtures.generate_fixtures import generate_all_fixtures
    generate_all_fixtures()


# ── Helpers ────────────────────────────────────────────────────────────────────

FIXTURES_DIR = Path(__file__).parent / "fixtures"


def fixture_path(name: str) -> Path:
    return FIXTURES_DIR / name


def open_pdf_for_upload(filename: str):
    """Open a fixture PDF as an in-memory bytes object for multipart upload."""
    path = fixture_path(filename)
    with open(path, "rb") as f:
        data = f.read()
    buf = io.BytesIO(data)
    buf.name = filename
    return buf


def docx_has_text(docx_path: str) -> bool:
    """Return True if the DOCX at docx_path contains at least some text."""
    try:
        from docx import Document
        doc = Document(docx_path)
        text = "\n".join(p.text for p in doc.paragraphs)
        return bool(text.strip())
    except Exception:
        return False


def docx_is_parseable(docx_path: str) -> bool:
    """Return True if python-docx can open and parse the DOCX file."""
    try:
        from docx import Document
        doc = Document(docx_path)
        _ = doc.paragraphs
        return True
    except Exception:
        return False


# ── PDF signature validator tests ──────────────────────────────────────────────

class PdfSignatureValidatorTest(TestCase):
    """Tests for the low-level PDF magic-byte validator."""

    def _tmp(self, content: bytes, suffix=".pdf") -> str:
        f = tempfile.NamedTemporaryFile(
            suffix=suffix, delete=False, dir=TEST_TEMP_DIR
        )
        f.write(content)
        f.close()
        return f.name

    def test_valid_pdf_signature_passes(self):
        path = self._tmp(b"%PDF-1.4 some valid content")
        validate_pdf_signature(path)  # must not raise

    def test_empty_file_raises(self):
        path = self._tmp(b"")
        with self.assertRaises(ConversionError) as ctx:
            validate_pdf_signature(path)
        self.assertIn("empty", str(ctx.exception).lower())

    def test_wrong_magic_bytes_raises(self):
        path = self._tmp(b"PK\x03\x04 fake zip file")
        with self.assertRaises(ConversionError) as ctx:
            validate_pdf_signature(path)
        self.assertIn("PDF", str(ctx.exception))

    def test_html_content_raises(self):
        path = self._tmp(b"<html><body>Not a PDF</body></html>")
        with self.assertRaises(ConversionError):
            validate_pdf_signature(path)

    def test_nonexistent_file_raises(self):
        with self.assertRaises(ConversionError) as ctx:
            validate_pdf_signature("/nonexistent/path/fake.pdf")
        self.assertIn("does not exist", str(ctx.exception))

    def test_output_validator_raises_for_missing_file(self):
        with self.assertRaises(ConversionError):
            validate_output_file("/tmp/does_not_exist_velto.docx")

    def test_output_validator_raises_for_empty_file(self):
        path = self._tmp(b"", suffix=".docx")
        with self.assertRaises(ConversionError) as ctx:
            validate_output_file(path)
        self.assertIn("empty", str(ctx.exception).lower())

    def test_output_validator_passes_for_nonempty_file(self):
        path = self._tmp(b"PK\x03\x04 fake docx content")
        validate_output_file(path)  # must not raise


# ── Engine unit tests (direct, no HTTP) ───────────────────────────────────────

@override_settings(TEMP_UPLOAD_DIR=TEST_TEMP_DIR)
class PdfToDocxEngineUnitTest(TestCase):
    """Direct engine tests — no HTTP, no serializers, just input/output paths."""

    def setUp(self):
        self.engine = PdfToDocxEngine()
        self.output_dir = Path(TEST_TEMP_DIR) / "engine_outputs"
        self.output_dir.mkdir(exist_ok=True)

    def _output_path(self, name: str) -> str:
        return str(self.output_dir / f"{uuid.uuid4().hex}_{name}")

    def test_engine_attributes(self):
        self.assertEqual(self.engine.source_format, "pdf")
        self.assertEqual(self.engine.target_format, "docx")

    def test_engine_repr(self):
        self.assertIn("pdf", repr(self.engine))
        self.assertIn("docx", repr(self.engine))

    def test_invalid_pdf_bytes_raises_conversion_error(self):
        """Non-PDF bytes must raise ConversionError, not a raw exception."""
        with tempfile.NamedTemporaryFile(
            suffix=".pdf", delete=False, dir=TEST_TEMP_DIR
        ) as f:
            f.write(b"This is not a PDF file at all")
            fake_path = f.name

        output_path = self._output_path("output.docx")
        with self.assertRaises(ConversionError):
            self.engine.convert(fake_path, output_path)

    def test_empty_file_raises_conversion_error(self):
        with tempfile.NamedTemporaryFile(
            suffix=".pdf", delete=False, dir=TEST_TEMP_DIR
        ) as f:
            fake_path = f.name  # 0 bytes

        output_path = self._output_path("output.docx")
        with self.assertRaises(ConversionError):
            self.engine.convert(fake_path, output_path)

    def test_missing_input_raises_conversion_error(self):
        with self.assertRaises(ConversionError):
            self.engine.convert("/nonexistent/path.pdf", self._output_path("out.docx"))

    def test_output_directory_is_created_if_missing(self):
        """Engine must create the output directory if it doesn't exist."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        nested_dir = Path(TEST_TEMP_DIR) / "nested" / "subdir"
        output_path = str(nested_dir / "output.docx")

        self.engine.convert(str(pdf_path), output_path)
        self.assertTrue(Path(output_path).exists())
        self.assertGreater(Path(output_path).stat().st_size, 0)

    def test_simple_text_pdf_converts_to_nonempty_docx(self):
        """Core integration test: a real text PDF produces a real DOCX."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        output_path = self._output_path("simple_text.docx")
        self.engine.convert(str(pdf_path), output_path)

        # Output must exist and be non-empty
        self.assertTrue(Path(output_path).exists(), "Output DOCX does not exist")
        self.assertGreater(Path(output_path).stat().st_size, 0, "Output DOCX is empty")

    def test_simple_text_pdf_produces_parseable_docx(self):
        """Output DOCX must be parseable by python-docx."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        output_path = self._output_path("parseable.docx")
        self.engine.convert(str(pdf_path), output_path)

        self.assertTrue(
            docx_is_parseable(output_path),
            "Output DOCX cannot be opened by python-docx",
        )

    def test_simple_text_pdf_produces_docx_with_text(self):
        """Output DOCX must contain some extractable text."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        output_path = self._output_path("with_text.docx")
        self.engine.convert(str(pdf_path), output_path)

        self.assertTrue(
            docx_has_text(output_path),
            "Output DOCX contains no extractable text",
        )

    def test_multipage_pdf_converts_successfully(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("multipage.pdf")
        if not pdf_path.exists():
            generate_multipage_pdf(pdf_path)

        output_path = self._output_path("multipage.docx")
        self.engine.convert(str(pdf_path), output_path)

        self.assertTrue(Path(output_path).exists())
        self.assertGreater(Path(output_path).stat().st_size, 0)
        self.assertTrue(docx_is_parseable(output_path))

    def test_table_pdf_converts_successfully(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("with_table.pdf")
        if not pdf_path.exists():
            generate_table_pdf(pdf_path)

        output_path = self._output_path("with_table.docx")
        self.engine.convert(str(pdf_path), output_path)

        self.assertTrue(Path(output_path).exists())
        self.assertGreater(Path(output_path).stat().st_size, 0)
        self.assertTrue(docx_is_parseable(output_path))

    def test_image_pdf_converts_successfully(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("with_image.pdf")
        if not pdf_path.exists():
            generate_image_pdf(pdf_path)

        output_path = self._output_path("with_image.docx")
        self.engine.convert(str(pdf_path), output_path)

        self.assertTrue(Path(output_path).exists())
        self.assertGreater(Path(output_path).stat().st_size, 0)
        self.assertTrue(docx_is_parseable(output_path))


# ── ConversionService integration tests ───────────────────────────────────────

@override_settings(TEMP_UPLOAD_DIR=TEST_TEMP_DIR)
class ConversionServicePhase2Test(TestCase):
    """Tests for the service layer: create_job, process_job, get_job_output, cleanup."""

    def _make_job(self, pdf_path: str, session_key: str = "test_session") -> ConversionJob:
        """Create a ConversionJob with a real staged input file."""
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename=Path(pdf_path).name,
            file_size_bytes=Path(pdf_path).stat().st_size,
            session_key=session_key,
            status=JobStatus.PENDING,
            input_path=pdf_path,
        )
        return job

    def test_process_job_completes_with_real_pdf(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        # Copy to temp dir to simulate staging
        import shutil
        staged = str(Path(TEST_TEMP_DIR) / f"{uuid.uuid4().hex}_simple_text.pdf")
        shutil.copy(str(pdf_path), staged)

        job = self._make_job(staged)
        result = ConversionService.process_job(job)

        self.assertEqual(result.status, JobStatus.COMPLETED)
        self.assertIsNotNone(result.completed_at)
        self.assertIsNotNone(result.output_path)
        self.assertIsNotNone(result.output_filename)
        self.assertIsNotNone(result.output_size_bytes)
        self.assertGreater(result.output_size_bytes, 0)

    def test_process_job_output_file_exists(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        import shutil
        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        staged = str(Path(TEST_TEMP_DIR) / f"{uuid.uuid4().hex}_simple_text.pdf")
        shutil.copy(str(pdf_path), staged)

        job = self._make_job(staged)
        result = ConversionService.process_job(job)

        self.assertEqual(result.status, JobStatus.COMPLETED)
        self.assertTrue(Path(result.output_path).exists())

    def test_process_job_failed_for_invalid_pdf(self):
        """A file with invalid PDF bytes must result in a FAILED job."""
        with tempfile.NamedTemporaryFile(
            suffix=".pdf", delete=False, dir=TEST_TEMP_DIR
        ) as f:
            f.write(b"Not a PDF - just garbage bytes 12345")

            bad_path = f.name

        job = self._make_job(bad_path)
        result = ConversionService.process_job(job)

        self.assertEqual(result.status, JobStatus.FAILED)
        self.assertIsNotNone(result.completed_at)
        self.assertTrue(len(result.error_message) > 0)
        # Must not expose internal paths or stack traces in error_message
        self.assertNotIn(TEST_TEMP_DIR, result.error_message)

    def test_process_job_skips_terminal_jobs(self):
        """Calling process_job on an already-completed job must be a no-op."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        import shutil
        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        staged = str(Path(TEST_TEMP_DIR) / f"{uuid.uuid4().hex}_simple_text.pdf")
        shutil.copy(str(pdf_path), staged)

        job = self._make_job(staged)
        result1 = ConversionService.process_job(job)
        self.assertEqual(result1.status, JobStatus.COMPLETED)

        # Second call must return immediately
        result2 = ConversionService.process_job(result1)
        self.assertEqual(result2.status, JobStatus.COMPLETED)

    def test_process_job_missing_input_file_fails(self):
        """If the staged input file is missing, job must fail cleanly."""
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename="ghost.pdf",
            session_key="test_session",
            status=JobStatus.PENDING,
            input_path="/nonexistent/path/ghost.pdf",
        )
        result = ConversionService.process_job(job)
        self.assertEqual(result.status, JobStatus.FAILED)
        self.assertTrue(len(result.error_message) > 0)

    def test_get_job_output_returns_none_for_pending_job(self):
        job = ConversionJob(status=JobStatus.PENDING, output_path="")
        self.assertIsNone(ConversionService.get_job_output(job))

    def test_get_job_output_returns_none_for_failed_job(self):
        job = ConversionJob(status=JobStatus.FAILED, output_path="")
        self.assertIsNone(ConversionService.get_job_output(job))

    def test_get_job_output_returns_none_if_file_missing(self):
        job = ConversionJob(
            status=JobStatus.COMPLETED,
            output_path="/nonexistent/output.docx",
        )
        self.assertIsNone(ConversionService.get_job_output(job))

    def test_get_job_output_returns_path_for_completed_job(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        import shutil
        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        staged = str(Path(TEST_TEMP_DIR) / f"{uuid.uuid4().hex}_simple_text.pdf")
        shutil.copy(str(pdf_path), staged)

        job = self._make_job(staged)
        result = ConversionService.process_job(job)
        self.assertEqual(result.status, JobStatus.COMPLETED)

        output_path = ConversionService.get_job_output(result)
        self.assertIsNotNone(output_path)
        self.assertTrue(Path(output_path).exists())

    def test_output_filename_is_sanitised(self):
        """Output filename must not expose absolute paths or dangerous characters."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        import shutil
        pdf_path = fixture_path("simple_text.pdf")
        if not pdf_path.exists():
            generate_simple_text_pdf(pdf_path)

        staged = str(Path(TEST_TEMP_DIR) / f"{uuid.uuid4().hex}_simple_text.pdf")
        shutil.copy(str(pdf_path), staged)

        job = self._make_job(staged)
        result = ConversionService.process_job(job)

        self.assertEqual(result.status, JobStatus.COMPLETED)
        # output_filename must not contain path separators
        self.assertNotIn("/", result.output_filename)
        self.assertNotIn("\\", result.output_filename)
        # Must end with .docx
        self.assertTrue(result.output_filename.endswith(".docx"))


# ── API endpoint Phase 2 tests ─────────────────────────────────────────────────

@override_settings(TEMP_UPLOAD_DIR=TEST_TEMP_DIR)
class ConversionApiPhase2Test(TestCase):
    """
    End-to-end API tests using real PDFs through the full HTTP stack.

    Exercises: POST /api/conversions/ → GET /api/conversions/{id}/ → GET download/
    """

    def setUp(self):
        self.client = APIClient()
        self.list_url = reverse("conversions:job-list-create")

    def _upload_real_pdf(self, filename: str, client=None) -> dict:
        """Upload a fixture PDF and return the response JSON."""
        c = client or self.client
        buf = open_pdf_for_upload(filename)
        response = c.post(
            self.list_url,
            data={"file": buf, "source_format": "pdf", "target_format": "docx"},
            format="multipart",
        )
        return response

    def test_upload_real_pdf_returns_non_pending_status(self):
        """After Phase 2 the POST should complete the conversion synchronously."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        self.assertIn(response.status_code, [
            status.HTTP_201_CREATED,
            status.HTTP_202_ACCEPTED,
        ])
        data = response.json()
        self.assertIn(data["status"], ["completed", "failed", "pending"])

    def test_upload_real_pdf_returns_completed_status(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()
        self.assertEqual(
            data["status"],
            "completed",
            f"Expected completed, got {data['status']}. Error: {data.get('error_message', '')}",
        )

    def test_completed_job_has_output_metadata(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()

        if data["status"] == "completed":
            self.assertIsNotNone(data["output_filename"])
            self.assertTrue(data["output_filename"].endswith(".docx"))
            self.assertIsNotNone(data["output_size_bytes"])
            self.assertGreater(data["output_size_bytes"], 0)

    def test_completed_job_has_download_url(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()

        if data["status"] == "completed":
            self.assertIsNotNone(data.get("download_url"))
            self.assertIn("/download/", data["download_url"])

    def test_download_url_does_not_expose_filesystem_path(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()

        if data["status"] == "completed" and data.get("download_url"):
            download_url = data["download_url"]
            # URL must be a relative API path, not a filesystem path
            self.assertNotIn(TEST_TEMP_DIR, download_url)
            self.assertNotIn("C:\\", download_url)
            self.assertNotIn("/tmp", download_url)
            self.assertTrue(download_url.startswith("/api/"))

    def test_download_endpoint_returns_docx_file(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()

        if data["status"] != "completed":
            self.skipTest(f"Conversion did not complete: {data.get('error_message')}")

        download_url = data["download_url"]
        dl_response = self.client.get(download_url)

        self.assertEqual(dl_response.status_code, status.HTTP_200_OK)
        self.assertIn("wordprocessingml", dl_response["Content-Type"])
        self.assertIn("attachment", dl_response.get("Content-Disposition", ""))

    def test_download_endpoint_file_is_valid_docx(self):
        """The downloaded bytes must be parseable as a real DOCX."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        response = self._upload_real_pdf("simple_text.pdf")
        data = response.json()

        if data["status"] != "completed":
            self.skipTest(f"Conversion did not complete: {data.get('error_message')}")

        dl_response = self.client.get(data["download_url"])
        self.assertEqual(dl_response.status_code, status.HTTP_200_OK)

        # Write the streamed bytes to a temp file and parse with python-docx
        with tempfile.NamedTemporaryFile(
            suffix=".docx", delete=False, dir=TEST_TEMP_DIR
        ) as tmp:
            for chunk in dl_response.streaming_content:
                tmp.write(chunk)
            tmp_path = tmp.name

        self.assertTrue(docx_is_parseable(tmp_path), "Downloaded file is not a valid DOCX")
        self.assertTrue(docx_has_text(tmp_path), "Downloaded DOCX contains no text")

    def test_multipage_pdf_converts_via_api(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("multipage.pdf").exists():
            generate_multipage_pdf(fixture_path("multipage.pdf"))

        response = self._upload_real_pdf("multipage.pdf")
        data = response.json()
        self.assertIn(data["status"], ["completed", "failed"])

    def test_table_pdf_converts_via_api(self):
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("with_table.pdf").exists():
            generate_table_pdf(fixture_path("with_table.pdf"))

        response = self._upload_real_pdf("with_table.pdf")
        data = response.json()
        self.assertIn(data["status"], ["completed", "failed"])


# ── Download security tests ────────────────────────────────────────────────────

@override_settings(TEMP_UPLOAD_DIR=TEST_TEMP_DIR)
class DownloadSecurityTest(TestCase):
    """Verify download endpoint security: session isolation, status guards."""

    def setUp(self):
        self.client_a = APIClient()
        self.client_b = APIClient()
        self.list_url = reverse("conversions:job-list-create")

    @staticmethod
    def _force_session(client: APIClient) -> str:
        """Force the client to have a session and return the session_key."""
        session = client.session
        session.create()
        client.cookies["velto_session"] = session.session_key
        return session.session_key

    def _upload(self, client, filename="simple_text.pdf"):
        if not fixture_path(filename).exists():
            generate_simple_text_pdf(fixture_path(filename))
        buf = open_pdf_for_upload(filename)
        return client.post(
            self.list_url,
            data={"file": buf, "source_format": "pdf", "target_format": "docx"},
            format="multipart",
        )

    def test_cross_session_download_returns_404(self):
        """Client B must not be able to download Client A's output."""
        if not REPORTLAB_AVAILABLE:
            self.skipTest("reportlab not installed")

        if not fixture_path("simple_text.pdf").exists():
            generate_simple_text_pdf(fixture_path("simple_text.pdf"))

        resp_a = self._upload(self.client_a)
        data_a = resp_a.json()

        if data_a["status"] != "completed":
            self.skipTest("Conversion did not complete -- skipping security test")

        download_url = data_a["download_url"]
        response = self.client_b.get(download_url)
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_download_pending_job_returns_non_200(self):
        """Attempting to download a pending job must not return 200."""
        session_key = self._force_session(self.client_a)
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename="pending.pdf",
            session_key=session_key,
            status=JobStatus.PENDING,
        )
        url = reverse("conversions:job-download", kwargs={"job_id": job.id})
        response = self.client_a.get(url)
        self.assertNotEqual(response.status_code, status.HTTP_200_OK)

    def test_download_failed_job_returns_422(self):
        """Attempting to download a failed job must return 422."""
        session_key = self._force_session(self.client_a)
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename="failed.pdf",
            session_key=session_key,
            status=JobStatus.FAILED,
            error_message="The PDF was corrupted.",
        )
        url = reverse("conversions:job-download", kwargs={"job_id": job.id})
        response = self.client_a.get(url)
        self.assertEqual(response.status_code, status.HTTP_422_UNPROCESSABLE_ENTITY)

    def test_download_nonexistent_job_returns_404(self):
        random_id = uuid.uuid4()
        url = reverse("conversions:job-download", kwargs={"job_id": random_id})
        response = self.client_a.get(url)
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_invalid_pdf_upload_results_in_failed_status(self):
        """Uploading a file with PDF extension but non-PDF content must result in failed."""
        buf = io.BytesIO(b"This is not a PDF file at all")
        buf.name = "fake.pdf"
        response = self.client_a.post(
            self.list_url,
            data={"file": buf, "source_format": "pdf", "target_format": "docx"},
            format="multipart",
        )
        # The response should either be 202 (failed conversion) or 400 (validation)
        self.assertIn(response.status_code, [
            status.HTTP_202_ACCEPTED,
            status.HTTP_400_BAD_REQUEST,
        ])
        if response.status_code == status.HTTP_202_ACCEPTED:
            data = response.json()
            self.assertEqual(data["status"], "failed")


# ── Engine registration tests ──────────────────────────────────────────────────

class EngineRegistrationTest(TestCase):
    """Verify the engine is registered with the global registry at startup."""

    def test_pdf_to_docx_engine_is_registered(self):
        """PdfToDocxEngine must be in the global registry after AppConfig.ready()."""
        from apps.conversions.engines.registry import engine_registry
        engine_cls = engine_registry.get("pdf", "docx")
        self.assertIsNotNone(
            engine_cls,
            "PdfToDocxEngine is not registered. Check ConversionsConfig.ready().",
        )
        self.assertIs(engine_cls, PdfToDocxEngine)

    def test_registered_engine_is_correct_class(self):
        from apps.conversions.engines.registry import engine_registry
        engine_cls = engine_registry.get("pdf", "docx")
        self.assertEqual(engine_cls.source_format, "pdf")
        self.assertEqual(engine_cls.target_format, "docx")
        self.assertTrue(issubclass(engine_cls, BaseConversionEngine))


# ── Model Phase 2 field tests ──────────────────────────────────────────────────

class ConversionJobPhase2ModelTest(TestCase):
    """Verify the new model fields are present and work correctly."""

    def test_new_fields_exist(self):
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename="test.pdf",
            session_key="test_session",
            input_path="/tmp/input.pdf",
            output_path="/tmp/output.docx",
            output_filename="test.docx",
            output_size_bytes=12345,
        )
        job.refresh_from_db()
        self.assertEqual(job.input_path, "/tmp/input.pdf")
        self.assertEqual(job.output_path, "/tmp/output.docx")
        self.assertEqual(job.output_filename, "test.docx")
        self.assertEqual(job.output_size_bytes, 12345)

    def test_new_fields_default_to_blank(self):
        job = ConversionJob.objects.create(
            source_format="pdf",
            target_format="docx",
            original_filename="test.pdf",
            session_key="test_session",
        )
        job.refresh_from_db()
        self.assertEqual(job.input_path, "")
        self.assertEqual(job.output_path, "")
        self.assertEqual(job.output_filename, "")
        self.assertIsNone(job.output_size_bytes)
